import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { getSession } from "@auth0/nextjs-auth0";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  try {
    const session = await getSession();
    if (!session) {
      return (
        <main className="flex flex-col gap-4 justify-center w-full h-screen grow items-center">
          <h1 className="text-4xl">PlantR</h1>
          <a className="btn btn-info" href="/api/auth/login">
            Login
          </a>
        </main>
      );
    }
    const { user } = session;
    return (
      <html lang="en">
        <UserProvider>
          <body className={inter.className}>
            <div className="navbar bg-base-100">
              <div className="flex-1">
                <a className="btn btn-ghost text-xl" href="/">
                  PlantR
                </a>
              </div>
              <div className="flex-none">
                <div className="dropdown dropdown-end">
                  <div
                    tabIndex={0}
                    role="button"
                    className="btn btn-ghost btn-circle avatar"
                  >
                    <div className="w-10 rounded-full">
                      <img
                        alt="Tailwind CSS Navbar component"
                        src={user.picture}
                      />
                    </div>
                  </div>
                  <ul
                    tabIndex={0}
                    className="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52"
                  >
                    <li className="p-2 text-gray-500">{user.name}</li>
                    <li className="p-2 text-gray-500">{user.email}</li>
                    <li>
                      <a href="/settings">Settings</a>
                    </li>
                    <li>
                      <a className="text-red-500" href="/api/auth/logout">
                        Logout
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            {children}
          </body>
        </UserProvider>
      </html>
    );
  } catch (error) {
    console.error(error);
    return (
      <main className="flex flex-col gap-4 justify-center w-full h-screen grow items-center">
        <h1 className="text-4xl">PlantR</h1>
        <a className="btn btn-info" href="/api/auth/login">
          Login
        </a>
      </main>
    );
  }
}
