import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { getSession } from "@auth0/nextjs-auth0";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  if (!session) {
    return (
      <main className="flex flex-col gap-4 justify-center w-full h-screen grow items-center">
        <h1 className="text-4xl">PlantR</h1>
        <a className="btn btn-info" href="/api/auth/login">
          Login
        </a>
      </main>
    );
  }
  return <p>Success</p>;
  );
}
